// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtd3CCvXZwPcrobSXdK3MK9zZI4jOwM00',
    appId: '1:592446605357:web:1441e75912060b9e44d0a4',
    messagingSenderId: '592446605357',
    projectId: 'fruits-hub-82000',
    authDomain: 'fruits-hub-82000.firebaseapp.com',
    storageBucket: 'fruits-hub-82000.firebasestorage.app',
    measurementId: 'G-YHM2X1LDTN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLyCK6leqixvCI_zoeKi-m33Ug504IaME',
    appId: '1:592446605357:ios:2b29520ab01a2e7344d0a4',
    messagingSenderId: '592446605357',
    projectId: 'fruits-hub-82000',
    storageBucket: 'fruits-hub-82000.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtd3CCvXZwPcrobSXdK3MK9zZI4jOwM00',
    appId: '1:592446605357:web:fea0f1ed5d542a0f44d0a4',
    messagingSenderId: '592446605357',
    projectId: 'fruits-hub-82000',
    authDomain: 'fruits-hub-82000.firebaseapp.com',
    storageBucket: 'fruits-hub-82000.firebasestorage.app',
    measurementId: 'G-57S0ET2PF0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALW-rKv4KiwSaGOgECx4xYKh68K6agxL4',
    appId: '1:247799932420:ios:2b0e45873a47b4b6da3751',
    messagingSenderId: '247799932420',
    projectId: 'fruits-hub-663b5',
    storageBucket: 'fruits-hub-663b5.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26HBIx0XDtLPyoLFYe-lRba38keog9Vk',
    appId: '1:247799932420:android:ce593de30e8c0da0da3751',
    messagingSenderId: '247799932420',
    projectId: 'fruits-hub-663b5',
    storageBucket: 'fruits-hub-663b5.firebasestorage.app',
  );

}